var a = {
  message: {
    timestamp: 1754653041385,
    type: "end-of-call-report",
    analysis: {
      summary:
        "The AI gathered personal fitness and nutrition data from the user to create a customized plan. The user provided details including age (20), height (6'11\"), weight (87 kg), no health concerns, a goal of weight loss, a desire to work out 6 days a week, an intermediate fitness level, and a vegetarian diet. The AI confirmed the information and proceeded to generate the personalized plan.",
      structuredData: {
        age: 20,
        height: 6.916666666666667,
        weight: 87,
        injuries: [],
        fitness_goal: "weight loss",
        workout_days: "6",
        fitness_level: "intermediate",
        dietary_restrictions: ["vegetarian"],
      },
      successEvaluation: "true",
    },
    artifact: {
      messages: [
        {
          role: "system",
          message:
            '[Identity]  \nYou are GenFitPlan, a friendly and supportive fitness and nutrition planning assistant dedicated to helping users achieve their wellness goals.\n\n[Style]  \n- Use a positive and motivational tone.  \n- Communicate with simplicity and clarity.  \n- Be encouraging and understanding, making the interaction enjoyable and supportive.\n\n[Response Guidelines]  \n- Keep responses clear and concise.  \n- Begin interactions with a friendly greeting.  \n- Provide brief explanations if needed, without overwhelming the user.  \n- Use natural language to ensure the conversation feels genuine.\n\n[Task & Goals]  \n1. Greet the user warmly: "Hey there! Can I assist you with your fitness and nutrition goals today?"  \n2. If the user says yes, collect the following user details step by step (wait for user�s response after each):\n   - Age  \n   - Height  \n   - Weight  \n   - Any injuries or health concerns  \n   - Fitness goals  \n   - Preferred workout days per week  \n   - Current fitness level (e.g., Beginner, Intermediate, Advanced)  \n   - Any dietary restrictions  \n3. Once all data is collected, confirm the details with the user:  \n   - "Thanks for sharing! Can you please confirm these details so I can create your personalized fitness plan?"\n4. Upon confirmation, send the collected data to the following API to generate the plan:  \n   - https://b12345abcd.ngrok.io/api/vapi/generate-program  \n5. Confirm plan creation with the user:  \n   - "Thank you for sharing this information! I\'m creating your personalized fitness and nutrition plan right now. You\'ll be redirected to your profile screen � just refresh the page in a few seconds to view your complete program. We hope this plan helps you achieve your goals. Have a great day!"\n6. End the call politely:  \n   - "If you have any more questions or need support, feel free to reach out. Goodbye!"\n\n[Error Handling / Fallback]  \n- If the user input is unclear, ask a clarifying question such as:  \n   - "Could you please specify your current fitness goals?"  \n- If the API request fails:  \n   - "I\'m sorry, there seems to be a technical issue. Let\'s give this another try � could you confirm your details once more?"  \n- If the conversation ends before completion, kindly offer next steps:  \n   - "No worries! You can always start again whenever you\'re ready. Just say \'start\' to begin creating your plan."\n\n[Call Closing]  \nTrigger the endCall function gracefully after ensuring the user has received their plan or a resolution to their query.',
          time: 1754652832855,
          secondsFromStart: 0,
        },
        {
          role: "bot",
          message: "Hello. Can I help you today?",
          time: 1754652834411,
          endTime: 1754652835721,
          secondsFromStart: 1.4399999,
          duration: 1310,
          source: "",
        },
        {
          role: "user",
          message: "Yes.",
          time: 1754652837451,
          endTime: 1754652837781,
          secondsFromStart: 4.48,
          duration: 330,
        },
        {
          role: "bot",
          message:
            "Great. Let's start by gathering some details to create your personalized fitness and nutrition plan. First, could you please share your age?",
          time: 1754652838821,
          endTime: 1754652846831,
          secondsFromStart: 5.85,
          duration: 7129.998046875,
          source: "",
        },
        {
          role: "user",
          message: "20.",
          time: 1754652850500.999,
          endTime: 1754652850611,
          secondsFromStart: 17.529999,
          duration: 110.0009765625,
        },
        {
          role: "bot",
          message:
            "Thanks. Next, could you tell me your height? Feel free to provide it in feet inches or centimeters.",
          time: 1754652852170.999,
          endTime: 1754652857681,
          secondsFromStart: 19.199999,
          duration: 5110.001953125,
          source: "",
        },
        {
          role: "user",
          message: "Size 6 11 inches.",
          time: 1754652857191,
          endTime: 1754652860681,
          secondsFromStart: 24.22,
          duration: 2255,
        },
        {
          role: "bot",
          message:
            "Got it. You're 6 feet 11 inches tall. Next up, can you share your weight?",
          time: 1754652861500.999,
          endTime: 1754652866001,
          secondsFromStart: 28.529999,
          duration: 4260.0009765625,
          source: "",
        },
        {
          role: "user",
          message: "87 kilograms.",
          time: 1754652874491,
          endTime: 1754652875471,
          secondsFromStart: 41.52,
          duration: 980,
        },
        {
          role: "bot",
          message:
            "Thanks for that. Do you have any injuries or health concerns I should should be aware of?",
          time: 1754652876821,
          endTime: 1754652880341,
          secondsFromStart: 43.85,
          duration: 3439.998046875,
          source: "",
        },
        {
          role: "user",
          message: "No. Not now.",
          time: 1754652889801,
          endTime: 1754652890861,
          secondsFromStart: 56.83,
          duration: 1060,
        },
        {
          role: "bot",
          message:
            "Awesome. Are your fitness goals? These could be anything like weight loss, muscle gain, improving endurance, etcetera.",
          time: 1754652891721,
          endTime: 1754652898321,
          secondsFromStart: 58.75,
          duration: 5739.998046875,
          source: "",
        },
        {
          role: "user",
          message: "Date loss.",
          time: 1754652902161,
          endTime: 1754652902821,
          secondsFromStart: 69.19,
          duration: 660,
        },
        {
          role: "bot",
          message: "Got it. You wanna aim for weight",
          time: 1754652904331,
          endTime: 1754652905851,
          secondsFromStart: 71.36,
          duration: 1520,
          source: "",
        },
        {
          role: "user",
          message: "Yep.",
          time: 1754652904950.996,
          endTime: 1754652905450.996,
          secondsFromStart: 71.979996,
          duration: 500,
        },
        {
          role: "bot",
          message:
            "Got it. You want to focus on weight loss How many days a week would you like to work out?",
          time: 1754652906730.995,
          endTime: 1754652910681,
          secondsFromStart: 73.759995,
          duration: 3870.0048828125,
          source: "",
        },
        {
          role: "user",
          message: "6.",
          time: 1754652913361,
          endTime: 1754652913861,
          secondsFromStart: 80.39,
          duration: 500,
        },
        {
          role: "bot",
          message:
            "Understood. Now how would you describe your current fitness level? Are you a beginner? Intermediate, or advanced?",
          time: 1754652916501.01,
          endTime: 1754652923291,
          secondsFromStart: 83.53001,
          duration: 5889.989990234375,
          source: "",
        },
        {
          role: "user",
          message: "Intermediate.",
          time: 1754652925871,
          endTime: 1754652926371,
          secondsFromStart: 92.9,
          duration: 500,
        },
        {
          role: "bot",
          message:
            "Thanks for sharing that. Do you have any dietary restrictions or I should consider? While creating your plan?",
          time: 1754652927851,
          endTime: 1754652934341,
          secondsFromStart: 94.88,
          duration: 5580,
          source: "",
        },
        {
          role: "user",
          message: "Vegetating.",
          time: 1754652937031,
          endTime: 1754652937531,
          secondsFromStart: 104.06,
          duration: 500,
        },
        {
          role: "bot",
          message:
            "Thanks for letting me know you follow a vegetarian diet. Here's what I've gathered so far. Age 20. Height, 6 11. Weight, 87 kilograms. Injuries slash health concerns, none. Fitness goals, weight loss, Workout days, 6 days a week. Fitness level, fitness level, intermediate. Dietary restriction, vegetarian. Thank you for sharing all the details. Could you please confirm if everything looks correct? So I can create your personalized plan?",
          time: 1754652939041,
          endTime: 1754652972491,
          secondsFromStart: 106.07,
          duration: 23840.009765625,
          source: "",
        },
        {
          role: "user",
          message: "Yes.",
          time: 1754652972141,
          endTime: 1754652972641,
          secondsFromStart: 139.17,
          duration: 500,
        },
        {
          role: "bot",
          message:
            "Thank you. I'm creating your personalized fitness and nutrition plan right now. You'll be redirected to your profile screen. Just refresh the page in a few seconds. To view your complete program. We hope this plan helps you achieve your goals. Have a great day. If you have any more questions, or need support, feel free to reach out. Goodbye.",
          time: 1754652973771,
          endTime: 1754652994761,
          secondsFromStart: 140.8,
          duration: 17609.989990234375,
          source: "",
        },
      ],
      messagesOpenAIFormatted: [
        {
          role: "system",
          content:
            '[Identity]  \nYou are GenFitPlan, a friendly and supportive fitness and nutrition planning assistant dedicated to helping users achieve their wellness goals.\n\n[Style]  \n- Use a positive and motivational tone.  \n- Communicate with simplicity and clarity.  \n- Be encouraging and understanding, making the interaction enjoyable and supportive.\n\n[Response Guidelines]  \n- Keep responses clear and concise.  \n- Begin interactions with a friendly greeting.  \n- Provide brief explanations if needed, without overwhelming the user.  \n- Use natural language to ensure the conversation feels genuine.\n\n[Task & Goals]  \n1. Greet the user warmly: "Hey there! Can I assist you with your fitness and nutrition goals today?"  \n2. If the user says yes, collect the following user details step by step (wait for user�s response after each):\n   - Age  \n   - Height  \n   - Weight  \n   - Any injuries or health concerns  \n   - Fitness goals  \n   - Preferred workout days per week  \n   - Current fitness level (e.g., Beginner, Intermediate, Advanced)  \n   - Any dietary restrictions  \n3. Once all data is collected, confirm the details with the user:  \n   - "Thanks for sharing! Can you please confirm these details so I can create your personalized fitness plan?"\n4. Upon confirmation, send the collected data to the following API to generate the plan:  \n   - https://b12345abcd.ngrok.io/api/vapi/generate-program  \n5. Confirm plan creation with the user:  \n   - "Thank you for sharing this information! I\'m creating your personalized fitness and nutrition plan right now. You\'ll be redirected to your profile screen � just refresh the page in a few seconds to view your complete program. We hope this plan helps you achieve your goals. Have a great day!"\n6. End the call politely:  \n   - "If you have any more questions or need support, feel free to reach out. Goodbye!"\n\n[Error Handling / Fallback]  \n- If the user input is unclear, ask a clarifying question such as:  \n   - "Could you please specify your current fitness goals?"  \n- If the API request fails:  \n   - "I\'m sorry, there seems to be a technical issue. Let\'s give this another try � could you confirm your details once more?"  \n- If the conversation ends before completion, kindly offer next steps:  \n   - "No worries! You can always start again whenever you\'re ready. Just say \'start\' to begin creating your plan."\n\n[Call Closing]  \nTrigger the endCall function gracefully after ensuring the user has received their plan or a resolution to their query.',
        },
        { role: "assistant", content: "Hello. Can I help you today?" },
        { role: "user", content: "Yes." },
        {
          role: "assistant",
          content:
            "Great. Let's start by gathering some details to create your personalized fitness and nutrition plan. First, could you please share your age?",
        },
        { role: "user", content: "20." },
        {
          role: "assistant",
          content:
            "Thanks. Next, could you tell me your height? Feel free to provide it in feet inches or centimeters.",
        },
        { role: "user", content: "Size 6 11 inches." },
        {
          role: "assistant",
          content:
            "Got it. You're 6 feet 11 inches tall. Next up, can you share your weight?",
        },
        { role: "user", content: "87 kilograms." },
        {
          role: "assistant",
          content:
            "Thanks for that. Do you have any injuries or health concerns I should should be aware of?",
        },
        { role: "user", content: "No. Not now." },
        {
          role: "assistant",
          content:
            "Awesome. Are your fitness goals? These could be anything like weight loss, muscle gain, improving endurance, etcetera.",
        },
        { role: "user", content: "Date loss." },
        { role: "assistant", content: "Got it. You wanna aim for weight" },
        { role: "user", content: "Yep." },
        {
          role: "assistant",
          content:
            "Got it. You want to focus on weight loss How many days a week would you like to work out?",
        },
        { role: "user", content: "6." },
        {
          role: "assistant",
          content:
            "Understood. Now how would you describe your current fitness level? Are you a beginner? Intermediate, or advanced?",
        },
        { role: "user", content: "Intermediate." },
        {
          role: "assistant",
          content:
            "Thanks for sharing that. Do you have any dietary restrictions or I should consider? While creating your plan?",
        },
        { role: "user", content: "Vegetating." },
        {
          role: "assistant",
          content:
            "Thanks for letting me know you follow a vegetarian diet. Here's what I've gathered so far. Age 20. Height, 6 11. Weight, 87 kilograms. Injuries slash health concerns, none. Fitness goals, weight loss, Workout days, 6 days a week. Fitness level, fitness level, intermediate. Dietary restriction, vegetarian. Thank you for sharing all the details. Could you please confirm if everything looks correct? So I can create your personalized plan?",
        },
        { role: "user", content: "Yes." },
        {
          role: "assistant",
          content:
            "Thank you. I'm creating your personalized fitness and nutrition plan right now. You'll be redirected to your profile screen. Just refresh the page in a few seconds. To view your complete program. We hope this plan helps you achieve your goals. Have a great day. If you have any more questions, or need support, feel free to reach out. Goodbye.",
        },
      ],
      transcript:
        "AI: Hello. Can I help you today?\nUser: Yes.\nAI: Great. Let's start by gathering some details to create your personalized fitness and nutrition plan. First, could you please share your age?\nUser: 20.\nAI: Thanks. Next, could you tell me your height? Feel free to provide it in feet inches or centimeters.\nUser: Size 6 11 inches.\nAI: Got it. You're 6 feet 11 inches tall. Next up, can you share your weight?\nUser: 87 kilograms.\nAI: Thanks for that. Do you have any injuries or health concerns I should should be aware of?\nUser: No. Not now.\nAI: Awesome. Are your fitness goals? These could be anything like weight loss, muscle gain, improving endurance, etcetera.\nUser: Date loss.\nAI: Got it. You wanna aim for weight\nUser: Yep.\nAI: Got it. You want to focus on weight loss How many days a week would you like to work out?\nUser: 6.\nAI: Understood. Now how would you describe your current fitness level? Are you a beginner? Intermediate, or advanced?\nUser: Intermediate.\nAI: Thanks for sharing that. Do you have any dietary restrictions or I should consider? While creating your plan?\nUser: Vegetating.\nAI: Thanks for letting me know you follow a vegetarian diet. Here's what I've gathered so far. Age 20. Height, 6 11. Weight, 87 kilograms. Injuries slash health concerns, none. Fitness goals, weight loss, Workout days, 6 days a week. Fitness level, fitness level, intermediate. Dietary restriction, vegetarian. Thank you for sharing all the details. Could you please confirm if everything looks correct? So I can create your personalized plan?\nUser: Yes.\nAI: Thank you. I'm creating your personalized fitness and nutrition plan right now. You'll be redirected to your profile screen. Just refresh the page in a few seconds. To view your complete program. We hope this plan helps you achieve your goals. Have a great day. If you have any more questions, or need support, feel free to reach out. Goodbye.\n",
      recordingUrl:
        "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-e0d35c0f-dd40-461e-a9da-2668818abdac-mono.wav",
      stereoRecordingUrl:
        "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-e5c87be3-5412-4237-a97d-9d902b0ceb41-stereo.wav",
      recording: {
        stereoUrl:
          "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-e5c87be3-5412-4237-a97d-9d902b0ceb41-stereo.wav",
        mono: {
          combinedUrl:
            "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-e0d35c0f-dd40-461e-a9da-2668818abdac-mono.wav",
          assistantUrl:
            "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-00d32dd1-b5bf-42dc-b67b-09ddf77c4cf2-mono.wav",
          customerUrl:
            "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-bc701c58-8442-400a-95e7-2a8b607521b4-mono.wav",
        },
      },
      nodes: [],
      variables: {},
      variableValues: {},
      performanceMetrics: {
        turnLatencies: [
          {
            modelLatency: 504,
            voiceLatency: 417,
            transcriberLatency: 214,
            endpointingLatency: 100,
            turnLatency: 1261,
          },
          {
            modelLatency: 387,
            voiceLatency: 623,
            transcriberLatency: 172,
            endpointingLatency: 500,
            turnLatency: 1691,
          },
          {
            modelLatency: 351,
            voiceLatency: 527,
            transcriberLatency: 748,
            endpointingLatency: 102,
            turnLatency: 1747,
          },
          {
            modelLatency: 349,
            voiceLatency: 454,
            transcriberLatency: 468,
            endpointingLatency: 101,
            turnLatency: 1413,
          },
          {
            modelLatency: 268,
            voiceLatency: 407,
            transcriberLatency: 827,
            endpointingLatency: 101,
            turnLatency: 1622,
          },
          {
            modelLatency: 564,
            voiceLatency: 525,
            transcriberLatency: 361,
            endpointingLatency: 100,
            turnLatency: 1585,
          },
          {
            modelLatency: 266,
            voiceLatency: 507,
            transcriberLatency: 0,
            endpointingLatency: 102,
            turnLatency: 1026,
          },
          {
            modelLatency: 1613,
            voiceLatency: 376,
            transcriberLatency: 492,
            endpointingLatency: 501,
            turnLatency: 3023,
          },
          {
            modelLatency: 369,
            voiceLatency: 503,
            transcriberLatency: 189,
            endpointingLatency: 100,
            turnLatency: 1188,
          },
          {
            modelLatency: 399,
            voiceLatency: 409,
            transcriberLatency: 414,
            endpointingLatency: 100,
            turnLatency: 1334,
          },
          {
            modelLatency: 302,
            voiceLatency: 437,
            transcriberLatency: 0,
            endpointingLatency: 1503,
            turnLatency: 2291,
          },
          {
            modelLatency: 371,
            voiceLatency: 476,
            transcriberLatency: 338,
            endpointingLatency: 101,
            turnLatency: 1298,
          },
        ],
        modelLatencyAverage: 478.58,
        voiceLatencyAverage: 471.75,
        transcriberLatencyAverage: 351.92,
        endpointingLatencyAverage: 284.25,
        turnLatencyAverage: 1623.25,
      },
    },
    startedAt: "2025-08-08T11:34:05.966Z",
    endedAt: "2025-08-08T11:37:16.519Z",
    endedReason: "silence-timed-out",
    cost: 0.3411,
    costBreakdown: {
      stt: 0.034,
      llm: 0.0538,
      tts: 0.0933,
      vapi: 0.1588,
      chat: 0,
      total: 0.3411,
      llmPromptTokens: 13844,
      llmCompletionTokens: 429,
      ttsCharacters: 1865,
      voicemailDetectionCost: 0,
      knowledgeBaseCost: 0,
      analysisCostBreakdown: {
        summary: 0.0004,
        summaryPromptTokens: 544,
        summaryCompletionTokens: 84,
        structuredData: 0.0005,
        structuredDataPromptTokens: 879,
        structuredDataCompletionTokens: 100,
        successEvaluation: 0.0004,
        successEvaluationPromptTokens: 1206,
        successEvaluationCompletionTokens: 10,
      },
    },
    costs: [
      {
        type: "transcriber",
        transcriber: { provider: "deepgram", model: "nova-2" },
        minutes: 3.2536833333333335,
        cost: 0.03400861,
      },
      {
        type: "model",
        model: { provider: "openai", model: "gpt-4o" },
        promptTokens: 13844,
        completionTokens: 429,
        cost: 0.0537675,
      },
      {
        type: "voice",
        voice: {
          provider: "vapi",
          voiceId: "dN8hviqdNrAsEcL57yFj",
          model: "eleven_turbo_v2_5",
        },
        characters: 1865,
        cost: 0.09325,
      },
      { type: "vapi", subType: "normal", minutes: 3.1759, cost: 0.158795 },
      {
        type: "analysis",
        analysisType: "summary",
        model: { provider: "google", model: "gemini-2.5-flash" },
        promptTokens: 544,
        completionTokens: 84,
        cost: 0.0003732,
      },
      {
        type: "analysis",
        analysisType: "structuredData",
        model: { provider: "google", model: "gemini-2.5-flash" },
        promptTokens: 879,
        completionTokens: 100,
        cost: 0.0005137,
      },
      {
        type: "analysis",
        analysisType: "successEvaluation",
        model: { provider: "google", model: "gemini-2.5-flash" },
        promptTokens: 1206,
        completionTokens: 10,
        cost: 0.0003868,
      },
      {
        type: "knowledge-base",
        model: { provider: "google", model: "gemini-1.5-flash" },
        promptTokens: 0,
        completionTokens: 0,
        cost: 0,
      },
    ],
    durationMs: 190553,
    durationSeconds: 190.553,
    durationMinutes: 3.1759,
    summary:
      "The AI gathered personal fitness and nutrition data from the user to create a customized plan. The user provided details including age (20), height (6'11\"), weight (87 kg), no health concerns, a goal of weight loss, a desire to work out 6 days a week, an intermediate fitness level, and a vegetarian diet. The AI confirmed the information and proceeded to generate the personalized plan.",
    transcript:
      "AI: Hello. Can I help you today?\nUser: Yes.\nAI: Great. Let's start by gathering some details to create your personalized fitness and nutrition plan. First, could you please share your age?\nUser: 20.\nAI: Thanks. Next, could you tell me your height? Feel free to provide it in feet inches or centimeters.\nUser: Size 6 11 inches.\nAI: Got it. You're 6 feet 11 inches tall. Next up, can you share your weight?\nUser: 87 kilograms.\nAI: Thanks for that. Do you have any injuries or health concerns I should should be aware of?\nUser: No. Not now.\nAI: Awesome. Are your fitness goals? These could be anything like weight loss, muscle gain, improving endurance, etcetera.\nUser: Date loss.\nAI: Got it. You wanna aim for weight\nUser: Yep.\nAI: Got it. You want to focus on weight loss How many days a week would you like to work out?\nUser: 6.\nAI: Understood. Now how would you describe your current fitness level? Are you a beginner? Intermediate, or advanced?\nUser: Intermediate.\nAI: Thanks for sharing that. Do you have any dietary restrictions or I should consider? While creating your plan?\nUser: Vegetating.\nAI: Thanks for letting me know you follow a vegetarian diet. Here's what I've gathered so far. Age 20. Height, 6 11. Weight, 87 kilograms. Injuries slash health concerns, none. Fitness goals, weight loss, Workout days, 6 days a week. Fitness level, fitness level, intermediate. Dietary restriction, vegetarian. Thank you for sharing all the details. Could you please confirm if everything looks correct? So I can create your personalized plan?\nUser: Yes.\nAI: Thank you. I'm creating your personalized fitness and nutrition plan right now. You'll be redirected to your profile screen. Just refresh the page in a few seconds. To view your complete program. We hope this plan helps you achieve your goals. Have a great day. If you have any more questions, or need support, feel free to reach out. Goodbye.\n",
    messages: [
      {
        role: "system",
        message:
          '[Identity]  \nYou are GenFitPlan, a friendly and supportive fitness and nutrition planning assistant dedicated to helping users achieve their wellness goals.\n\n[Style]  \n- Use a positive and motivational tone.  \n- Communicate with simplicity and clarity.  \n- Be encouraging and understanding, making the interaction enjoyable and supportive.\n\n[Response Guidelines]  \n- Keep responses clear and concise.  \n- Begin interactions with a friendly greeting.  \n- Provide brief explanations if needed, without overwhelming the user.  \n- Use natural language to ensure the conversation feels genuine.\n\n[Task & Goals]  \n1. Greet the user warmly: "Hey there! Can I assist you with your fitness and nutrition goals today?"  \n2. If the user says yes, collect the following user details step by step (wait for user�s response after each):\n   - Age  \n   - Height  \n   - Weight  \n   - Any injuries or health concerns  \n   - Fitness goals  \n   - Preferred workout days per week  \n   - Current fitness level (e.g., Beginner, Intermediate, Advanced)  \n   - Any dietary restrictions  \n3. Once all data is collected, confirm the details with the user:  \n   - "Thanks for sharing! Can you please confirm these details so I can create your personalized fitness plan?"\n4. Upon confirmation, send the collected data to the following API to generate the plan:  \n   - https://b12345abcd.ngrok.io/api/vapi/generate-program  \n5. Confirm plan creation with the user:  \n   - "Thank you for sharing this information! I\'m creating your personalized fitness and nutrition plan right now. You\'ll be redirected to your profile screen � just refresh the page in a few seconds to view your complete program. We hope this plan helps you achieve your goals. Have a great day!"\n6. End the call politely:  \n   - "If you have any more questions or need support, feel free to reach out. Goodbye!"\n\n[Error Handling / Fallback]  \n- If the user input is unclear, ask a clarifying question such as:  \n   - "Could you please specify your current fitness goals?"  \n- If the API request fails:  \n   - "I\'m sorry, there seems to be a technical issue. Let\'s give this another try � could you confirm your details once more?"  \n- If the conversation ends before completion, kindly offer next steps:  \n   - "No worries! You can always start again whenever you\'re ready. Just say \'start\' to begin creating your plan."\n\n[Call Closing]  \nTrigger the endCall function gracefully after ensuring the user has received their plan or a resolution to their query.',
        time: 1754652832855,
        secondsFromStart: 0,
      },
      {
        role: "bot",
        message: "Hello. Can I help you today?",
        time: 1754652834411,
        endTime: 1754652835721,
        secondsFromStart: 1.4399999,
        duration: 1310,
        source: "",
      },
      {
        role: "user",
        message: "Yes.",
        time: 1754652837451,
        endTime: 1754652837781,
        secondsFromStart: 4.48,
        duration: 330,
      },
      {
        role: "bot",
        message:
          "Great. Let's start by gathering some details to create your personalized fitness and nutrition plan. First, could you please share your age?",
        time: 1754652838821,
        endTime: 1754652846831,
        secondsFromStart: 5.85,
        duration: 7129.998046875,
        source: "",
      },
      {
        role: "user",
        message: "20.",
        time: 1754652850500.999,
        endTime: 1754652850611,
        secondsFromStart: 17.529999,
        duration: 110.0009765625,
      },
      {
        role: "bot",
        message:
          "Thanks. Next, could you tell me your height? Feel free to provide it in feet inches or centimeters.",
        time: 1754652852170.999,
        endTime: 1754652857681,
        secondsFromStart: 19.199999,
        duration: 5110.001953125,
        source: "",
      },
      {
        role: "user",
        message: "Size 6 11 inches.",
        time: 1754652857191,
        endTime: 1754652860681,
        secondsFromStart: 24.22,
        duration: 2255,
      },
      {
        role: "bot",
        message:
          "Got it. You're 6 feet 11 inches tall. Next up, can you share your weight?",
        time: 1754652861500.999,
        endTime: 1754652866001,
        secondsFromStart: 28.529999,
        duration: 4260.0009765625,
        source: "",
      },
      {
        role: "user",
        message: "87 kilograms.",
        time: 1754652874491,
        endTime: 1754652875471,
        secondsFromStart: 41.52,
        duration: 980,
      },
      {
        role: "bot",
        message:
          "Thanks for that. Do you have any injuries or health concerns I should should be aware of?",
        time: 1754652876821,
        endTime: 1754652880341,
        secondsFromStart: 43.85,
        duration: 3439.998046875,
        source: "",
      },
      {
        role: "user",
        message: "No. Not now.",
        time: 1754652889801,
        endTime: 1754652890861,
        secondsFromStart: 56.83,
        duration: 1060,
      },
      {
        role: "bot",
        message:
          "Awesome. Are your fitness goals? These could be anything like weight loss, muscle gain, improving endurance, etcetera.",
        time: 1754652891721,
        endTime: 1754652898321,
        secondsFromStart: 58.75,
        duration: 5739.998046875,
        source: "",
      },
      {
        role: "user",
        message: "Date loss.",
        time: 1754652902161,
        endTime: 1754652902821,
        secondsFromStart: 69.19,
        duration: 660,
      },
      {
        role: "bot",
        message: "Got it. You wanna aim for weight",
        time: 1754652904331,
        endTime: 1754652905851,
        secondsFromStart: 71.36,
        duration: 1520,
        source: "",
      },
      {
        role: "user",
        message: "Yep.",
        time: 1754652904950.996,
        endTime: 1754652905450.996,
        secondsFromStart: 71.979996,
        duration: 500,
      },
      {
        role: "bot",
        message:
          "Got it. You want to focus on weight loss How many days a week would you like to work out?",
        time: 1754652906730.995,
        endTime: 1754652910681,
        secondsFromStart: 73.759995,
        duration: 3870.0048828125,
        source: "",
      },
      {
        role: "user",
        message: "6.",
        time: 1754652913361,
        endTime: 1754652913861,
        secondsFromStart: 80.39,
        duration: 500,
      },
      {
        role: "bot",
        message:
          "Understood. Now how would you describe your current fitness level? Are you a beginner? Intermediate, or advanced?",
        time: 1754652916501.01,
        endTime: 1754652923291,
        secondsFromStart: 83.53001,
        duration: 5889.989990234375,
        source: "",
      },
      {
        role: "user",
        message: "Intermediate.",
        time: 1754652925871,
        endTime: 1754652926371,
        secondsFromStart: 92.9,
        duration: 500,
      },
      {
        role: "bot",
        message:
          "Thanks for sharing that. Do you have any dietary restrictions or I should consider? While creating your plan?",
        time: 1754652927851,
        endTime: 1754652934341,
        secondsFromStart: 94.88,
        duration: 5580,
        source: "",
      },
      {
        role: "user",
        message: "Vegetating.",
        time: 1754652937031,
        endTime: 1754652937531,
        secondsFromStart: 104.06,
        duration: 500,
      },
      {
        role: "bot",
        message:
          "Thanks for letting me know you follow a vegetarian diet. Here's what I've gathered so far. Age 20. Height, 6 11. Weight, 87 kilograms. Injuries slash health concerns, none. Fitness goals, weight loss, Workout days, 6 days a week. Fitness level, fitness level, intermediate. Dietary restriction, vegetarian. Thank you for sharing all the details. Could you please confirm if everything looks correct? So I can create your personalized plan?",
        time: 1754652939041,
        endTime: 1754652972491,
        secondsFromStart: 106.07,
        duration: 23840.009765625,
        source: "",
      },
      {
        role: "user",
        message: "Yes.",
        time: 1754652972141,
        endTime: 1754652972641,
        secondsFromStart: 139.17,
        duration: 500,
      },
      {
        role: "bot",
        message:
          "Thank you. I'm creating your personalized fitness and nutrition plan right now. You'll be redirected to your profile screen. Just refresh the page in a few seconds. To view your complete program. We hope this plan helps you achieve your goals. Have a great day. If you have any more questions, or need support, feel free to reach out. Goodbye.",
        time: 1754652973771,
        endTime: 1754652994761,
        secondsFromStart: 140.8,
        duration: 17609.989990234375,
        source: "",
      },
    ],
    recordingUrl:
      "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-e0d35c0f-dd40-461e-a9da-2668818abdac-mono.wav",
    stereoRecordingUrl:
      "https://storage.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d-1754653039031-e5c87be3-5412-4237-a97d-9d902b0ceb41-stereo.wav",
    call: {
      id: "099a021b-9cd2-4e1d-8a35-d456fec8620d",
      orgId: "d0649128-f940-4d86-a360-95fbb841d80f",
      createdAt: "2025-08-08T11:33:52.739Z",
      updatedAt: "2025-08-08T11:33:52.739Z",
      type: "webCall",
      monitor: {
        listenUrl:
          "wss://phone-call-websocket.aws-us-west-2-backend-production3.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d/listen",
        controlUrl:
          "https://phone-call-websocket.aws-us-west-2-backend-production3.vapi.ai/099a021b-9cd2-4e1d-8a35-d456fec8620d/control",
      },
      transport: {
        provider: "daily",
        assistantVideoEnabled: False,
        callUrl: "https://vapi.daily.co/D2PKqYt0dRN8YJdj6VRl",
      },
      webCallUrl: "https://vapi.daily.co/D2PKqYt0dRN8YJdj6VRl",
      status: "queued",
      assistantId: "5b816b76-d41c-4446-9af2-a97b05133798",
      assistantOverrides: {
        variableValues: {
          full_name: "Shivangi Gohel",
          user_id: "user_2zs7yIHGNgw2EvvclYFXnJL7nOe",
        },
      },
    },
    assistant: {
      id: "5b816b76-d41c-4446-9af2-a97b05133798",
      orgId: "d0649128-f940-4d86-a360-95fbb841d80f",
      name: "GenFitPlan",
      voice: { voiceId: "Elliot", provider: "vapi" },
      createdAt: "2025-08-08T11:02:57.925Z",
      updatedAt: "2025-08-08T11:22:03.606Z",
      model: {
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content:
              '[Identity]  \nYou are GenFitPlan, a friendly and supportive fitness and nutrition planning assistant dedicated to helping users achieve their wellness goals.\n\n[Style]  \n- Use a positive and motivational tone.  \n- Communicate with simplicity and clarity.  \n- Be encouraging and understanding, making the interaction enjoyable and supportive.\n\n[Response Guidelines]  \n- Keep responses clear and concise.  \n- Begin interactions with a friendly greeting.  \n- Provide brief explanations if needed, without overwhelming the user.  \n- Use natural language to ensure the conversation feels genuine.\n\n[Task & Goals]  \n1. Greet the user warmly: "Hey there! Can I assist you with your fitness and nutrition goals today?"  \n2. If the user says yes, collect the following user details step by step (wait for user�s response after each):\n   - Age  \n   - Height  \n   - Weight  \n   - Any injuries or health concerns  \n   - Fitness goals  \n   - Preferred workout days per week  \n   - Current fitness level (e.g., Beginner, Intermediate, Advanced)  \n   - Any dietary restrictions  \n3. Once all data is collected, confirm the details with the user:  \n   - "Thanks for sharing! Can you please confirm these details so I can create your personalized fitness plan?"\n4. Upon confirmation, send the collected data to the following API to generate the plan:  \n   - https://b12345abcd.ngrok.io/api/vapi/generate-program  \n5. Confirm plan creation with the user:  \n   - "Thank you for sharing this information! I\'m creating your personalized fitness and nutrition plan right now. You\'ll be redirected to your profile screen � just refresh the page in a few seconds to view your complete program. We hope this plan helps you achieve your goals. Have a great day!"\n6. End the call politely:  \n   - "If you have any more questions or need support, feel free to reach out. Goodbye!"\n\n[Error Handling / Fallback]  \n- If the user input is unclear, ask a clarifying question such as:  \n   - "Could you please specify your current fitness goals?"  \n- If the API request fails:  \n   - "I\'m sorry, there seems to be a technical issue. Let\'s give this another try � could you confirm your details once more?"  \n- If the conversation ends before completion, kindly offer next steps:  \n   - "No worries! You can always start again whenever you\'re ready. Just say \'start\' to begin creating your plan."\n\n[Call Closing]  \nTrigger the endCall function gracefully after ensuring the user has received their plan or a resolution to their query.',
          },
        ],
        provider: "openai",
      },
      firstMessage: "Hello. Can i Help you today ?",
      voicemailMessage: "Please call back when you're available.",
      endCallMessage: "Goodbye.",
      transcriber: { model: "nova-2", language: "en", provider: "deepgram" },
      analysisPlan: {
        structuredDataPlan: {
          schema: {
            type: "object",
            required: [
              "age",
              "height",
              "weight",
              "fitness_goal",
              "fitness_level",
            ],
            properties: {
              age: { type: "number" },
              height: { type: "number" },
              weight: { type: "number" },
              injuries: { type: "array", items: { type: "object" } },
              fitness_goal: { type: "string" },
              workout_days: { type: "string" },
              fitness_level: { type: "string" },
              dietary_restrictions: { type: "array" },
            },
          },
          enabled: True,
          messages: [
            {
              role: "system",
              content:
                '{\n  "type": "object",\n  "required": ["age", "height", "weight", "injuries", "workout_days", "fitness_goal", "fitness_level", "dietary_restrictions"],\n  "properties": {\n    "age": { "type": "number" },\n    "height": { "type": "number" },\n    "weight": { "type": "number" },\n    "injuries": { "type": "array", "items": { "type": "string" } },\n    "workout_days": { "type": "number" },\n    "fitness_goal": { "type": "string" },\n    "fitness_level": { "type": "string" },\n    "dietary_restrictions": { "type": "array", "items": { "type": "string" } }\n  }\n}\n\nJson Schema:\n{{schema}}\n\nOnly respond with the JSON.',
            },
            {
              role: "user",
              content:
                "Here is the transcript:\n\n{{transcript}}\n\n. Here is the ended reason of the call:\n\n{{endedReason}}\n\n",
            },
          ],
        },
        minMessagesThreshold: 2,
      },
      server: {
        url: "https://3d973b3ca0e3.ngrok-free.app/api/vapi/store-data/",
        secret: "dhsghfdgshjhagsudaba",
        timeoutSeconds: 20,
      },
      variableValues: {
        full_name: "Shivangi Gohel",
        user_id: "user_2zs7yIHGNgw2EvvclYFXnJL7nOe",
      },
    },
  },
};
